clusterName: pulsar
affinity:
  anti_affinity: true
components:
  zookeeper: true
  bookkeeper: true
  autorecovery: true
  broker: true
  functions: true
  proxy: true
  toolset: true
  pulsar_manager: false
  sql_worker: false
  kop: false
  mop: false
  pulsar_detector: false
  superset: false
volumes:
  persistence: true
  local_storage: false
imagePullSecrets:
- name: jfrog
- name: oemreg

monitoring:
  prometheus: false
  grafana: false
  node_exporter: false
  alert_manager: false
  loki: false
  datadog: false

zookeeper:
  replicaCount: 5
  resources:
    requests:
      memory: 300Mi
      cpu: 0.1
  affinity:
    anti_affinity: true
    # this is affection hosts only
    type: requiredDuringSchedulingIgnoredDuringExecution
    # possible values are "topology.kubernetes.io/zone" or "kubernetes.io/hostname"
    enableProdMode: true
  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    data:
      name: data
      size: 12Gi
  nodeSelector:
    dwnapp: pulsar
  affinity:
    anti_affinity: true
    # this is affection hosts only
    type: requiredDuringSchedulingIgnoredDuringExecution
bookkeeper:
  #3 replicas is required by default settings, ajdust in the Helm chart if undesirable
  replicaCount: 6
  resources:
    requests:
      memory: 400Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx2048m -XX:MaxDirectMemorySize=512m
    numAddWorkerThreads: "2"
  nodeSelector:
    dwnapp: pulsar
  affinity:
    anti_affinity: true
    # this is affection hosts only
    type: requiredDuringSchedulingIgnoredDuringExecution
    # possible values are "topology.kubernetes.io/zone" or "kubernetes.io/hostname"
    enableProdMode: true

broker:
  replicaCount: 5
  resources:
    requests:
      memory: 1Gi
      cpu: 750m
  nodeSelector:
    dwnapp: pulsar
  affinity:
    anti_affinity: true
    # this is affection hosts only
    type: requiredDuringSchedulingIgnoredDuringExecution
    # possible values are "topology.kubernetes.io/zone" or "kubernetes.io/hostname"
    enableProdMode: true
  configData:
    PULSAR_MEM: >
      -Xms512m -Xmx4096m -XX:MaxDirectMemorySize=1024m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -Dio.netty.leakDetectionLevel=disabled
      -Dio.netty.recycler.linkCapacity=1024
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+AggressiveOpts
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=50
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
    # @deprecated:
    # 1. You can use a service account to assume an IAM role to access S3 bucket
    # 2. You can use a k8s secret to reference AWS credentials. See `offload.s3.secret`
    # AWS_ACCESS_KEY_ID: "[YOUR AWS ACCESS KEY ID]"
    # AWS_SECRET_ACCESS_KEY: "[YOUR SECRET]"
    managedLedgerDefaultEnsembleSize: "3"
    managedLedgerDefaultWriteQuorum: "3"
    managedLedgerDefaultAckQuorum: "2"
    brokerDeleteInactiveTopicsEnabled: "false"
    defaultRetentionTimeInMinutes: "4320"
    allowAutoTopicCreation: "false"
    allowAutoTopicCreationType: "partitioned"
    defaultNumPartitions: "3"
    brokerDeleteInactiveTopicsFrequencySeconds: "36000"
    brokerDeleteInactiveTopicsMaxInactiveDurationSeconds: "1209600"
    subscriptionExpirationTimeMinutes: "4320"
    superUserRoles: "dwn-mothership-admin,dwn-tenant-admin"
proxy:
  resources:
    requests:
      memory: 600Mi
      cpu: 300m
  nodeSelector:
    dwnapp: pulsar
  affinity:
    anti_affinity: true
    # this is affection hosts only
    type: requiredDuringSchedulingIgnoredDuringExecution
    # possible values are "topology.kubernetes.io/zone" or "kubernetes.io/hostname"
    enableProdMode: true

  service:
    type: "ClusterIP"
  replicaCount: 2
  configData:
    PULSAR_MEM: >
      -Xms512m -Xmx4096m -XX:MaxDirectMemorySize=1024m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -Dio.netty.leakDetectionLevel=disabled
      -Dio.netty.recycler.linkCapacity=1024
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+AggressiveOpts
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=50
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
auth:
  superUsers:
    # broker to broker communication
    broker: "broker-admin"
    # proxy to broker communication
    proxy: "proxy-admin"
    # websocket proxy to broker communication
    websocket: "ws-admin"
    # pulsar-admin client to broker/proxy communication
    client: "admin"
    # pulsar-manager to broker/proxy communication
    pulsar_manager: "pulsar-manager-admin"

## Images
##
## Control what images to use for each component
images:
  zookeeper:
    # repository: darwinium.jfrog.io/dwn-docker/pulsar-all
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  bookie:
    # repository: darwinium.jfrog.io/dwn-docker/pulsar-all
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  autorecovery:
    # repository: darwinium.jfrog.io/dwn-docker/pulsar-all
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  broker:    # repository: darwinium.jfrog.io/dwn-docker/pulsar-all
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  proxy:
    # repository: darwinium.jfrog.io/dwn-docker/pulsar-all
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
  functions:
    # repository: darwinium.jfrog.io/dwn-docker/pulsar-all
    repository: apachepulsar/pulsar-all
    tag: 2.10.1
    pullPolicy: IfNotPresent
